website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import Lecturers, Departments, Faculties, Students, Levels
from dependencies.dependent import db
from flask_login import login_user, login_required, logout_user, current_user
from website.forms import RegisterForm, loginForm, studentEnrollForm, studentLogin

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = loginForm()
    if form.validate_on_submit():
        attempted_user = Lecturers.query.filter_by(id=form.staff_no.data).first()
        if attempted_user and attempted_user.check_password_correctness(
            attempted_password=form.password.data
        ):
            login_user(attempted_user)
            flash(f'Success! You are logged in as: {attempted_user.first_name}', category='success')
            return redirect(url_for('views.dashboard'))
        else:
            flash('Username and password are not match! Please try again', category='danger')
    return render_template('login.html', form=form, user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out!', category='info')
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    form = RegisterForm()
    if request.method == 'POST':
        form.faculty.choices = [(faculty.id, faculty.faculty) 
                                for faculty in Faculties.query.all()]
        faculty_id = form.faculty.data
        form.department.choices = [(department.department, department.department) 
                                   for department in Departments.query.
                                   filter_by(faculty_id=faculty_id).all()]
        if form.validate_on_submit():
            department_id = (Departments.query.
                            filter_by(department=form.department.data).
                            first()).id
            user_to_create = Lecturers(
                    id=form.staff_no.data,
                    first_name=form.first_name.data,
                    last_name=form.last_name.data,
                    email=form.email_address.data,
                    password=form.password.data,
                    faculty_id=form.faculty.data,
                    department_id=department_id
                )
            db.session.add(user_to_create)
            db.session.commit()
            flash(f'Account successfully created, You are now logged in as: \
                  {user_to_create.first_name}', category='success')
            login_user(user_to_create)
            return redirect(url_for('views.dashboard'))
        if form.errors != {}:
            for err_msg in form.errors.values():
                flash(f'There was an error with creating an account: {err_msg}', category='danger')
        
    return render_template('sign_up.html', form=form, user=current_user)

@auth.route('/student-enroll', methods=['GET', 'POST'])
def enroll():
    form = studentEnrollForm()
    form.level.choices = [(level.id, level.level) for level in Levels.query.all()]
    if request.method == 'POST':
        form.faculty.choices = [(faculty.id, faculty.faculty) 
                                for faculty in Faculties.query.all()]
        faculty_id = form.faculty.data
        form.department.choices = [(department.department, department.department) 
                                   for department in Departments.query.
                                   filter_by(faculty_id=faculty_id).all()]
        if form.validate_on_submit():
            department_id = (Departments.query.
                            filter_by(department=form.department.data).
                            first()).id
            student_to_create = Students(
                matric_no = form.matric_no.data,
                first_name=form.first_name.data,
                last_name=form.last_name.data,
                level_id = form.level.data,
                faculty_id=form.faculty.data,
                department_id=department_id
            )
            db.session.add(student_to_create)
            db.session.commit()
            flash('Enrolled successfully!', category='info')
            return redirect(url_for('views.student_dashboard', matric_no=student_to_create.matric_no))
        if form.errors != {}:
            for err_msg in form.errors.value():
                flash(f'There was an error with enrolling: {err_msg}', category='danger')

    return render_template('student_enroll.html', form=form, user=current_user)

@auth.route('/student-login', methods=['GET', 'POST'])
def student_login():
    form = studentLogin()
    if form.validate_on_submit():
        attempted_user = Students.query.get(form.matric_no.data)
        if attempted_user and attempted_user.check_first_name_correctness(
            submitted_name=form.first_name.data
        ):
            flash(f'Success! You are logged in as: {attempted_user.first_name}', category='success')
            return redirect(url_for('views.student_dashboard', matric_no=attempted_user.matric_no))
        else:
            flash('Account not found! Please try again', category='danger')
    return render_template('student_login.html', form=form, user=current_user)

website/templates/attendance.html
{% extends "base.html" %}

{% block title %}
  Dashboard
{% endblock %}

{% block head %}
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"></script>
    <script type="text/javascript">
        const winUrl = new URL(window.location.href);
        const courseValue = winUrl.searchParams.get("course");

        var socket = io.connect('http://' + document.domain + ':' + location.port + '/websocket', 
                        {query: {courseCode: courseValue}});

        socket.on('connect', function() {
            console.log('Connected to server via WebSocket');
        });

        socket.on('attendance_status', function(data) {
            var statusElement = document.getElementById('attendance-status');
            statusElement.textContent = 'Attendance Status: ' + data.status;
        });

        socket.on('attendance_result', function(data) {
            var resultElement = document.getElementById('attendance-result');
            if ('error' in data) {
                resultElement.textContent = 'Error: ' + data.error;
                // todo: this might be a console.log()
            } else {
                resultElement.textContent = 'Name: ' + data.name + ', Matric Number: ' + data.matric_no;
            }
        });

        socket.on('server_message', function(data) {
            console.log(data.message)
        });

        function startAttendance() {
            socket.emit('start_attendance',);
        }

        function stopAttendance() {
            socket.emit('stop_attendance');
        }
    </script>
</head> 
{% endblock %}

{% block content %}
<body>
    <h1>{{ course.course_title }} ({{ course.course_code }})<br>Attendance</h1>
    <p id="attendance-status">Attendance Status: Yet to start</p>
    <button class="btn btn-info mb-3" onclick="startAttendance()">Start Attendance</button>
    <button class="btn btn-warning mb-3"onclick="stopAttendance()">Stop Attendance</button>
    <p id="attendance-result">Attendance Result:</p>
</body>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
    integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <title>{% block title %}Home{% endblock %}</title>

  <script
  type="text/javascript"
  src="{{ url_for('static', filename='index.js') }}"
  ></script>

  <script 
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" 
  crossorigin="anonymous"
  ></script>

  {% block head %}
  {% endblock %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <div class="navbar-nav">
        {% if user.is_authenticated %}
        <a class="nav-item nav-link" id="Home" href="/">Home</a>
        <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
        {% else %}
        <a class="nav-item nav-link" id="login" href="/login">Login</a>
        <a class="nav-item nav-link" id="sign up" href="/sign-up">Sign up</a>
        {% endif %}
      </div>
    </div>
</nav>

{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="'button" class="btn-close" data-bs-dismiss="alert" 
        aria-label="close"></button>
    </div>
    {% endfor %}
  {% endif%}
  {% endwith %}

<div class="container">
  {% block content%}
  {% endblock %}
</div>

</body>
</html>

website/templates/dashboard.html
{% extends "base.html" %}

{% block title %}
  Dashboard
{% endblock %}

{% block content %}
<body>
  <div class="text-center">
    <h1 class="mb-3">Welcome To Your Dashboard {{ user.first_name }}! </h1>
    <h5 class="mb-1">You can take attendance for courses you take, but add them to
      the list first by clicking on the 'add new course' button. you can also get 
      attendance records for each course. 
    </h5>
  </div>
  <h2 class="">Courses</h2>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Course Code</th>
        <th scope="col">Course Title</th>
        <th scope="col">Take Attendance</th>
        <th scope="col">Attendance Records</th>
      </tr>
    </thead>
    <tbody>
      {% for course in courses %}
      <tr>
        <td>{{ course.course_code }}</td>
        <td>{{ course.course_title }}</td>
        <td><a class="btn btn-primary btn-sm" 
          href="/take-attendance?course={{course.course_code}}" 
          role="button">Take Attendance</a>
        </td>
        <td><a class="btn btn-info btn-sm" href="/get-records/{{ course.course_code }}" role="button">Download Record</a>
        </td>
      </tr>
      {% endfor %}
      
    </tbody>
  </table>

  <button type="button" class="btn btn-primary" data-bs-toggle="modal" 
    data-bs-target="#addCourseModal">Add New Course
  </button>

  <!-- Add course Modal -->
  <div class="modal fade modal-lg" id="addCourseModal" tabindex="-1" 
    aria-labelledby="addCourseModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="addCourseModalLabel">
            Add a Course to your Dashboard</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" 
            aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form method="POST" class="form-register">
            {{ form.hidden_tag() }}
            <div class="form-floating mb-3">
              {{ form.course_code(class="form-control", placeholder="Course Code") }}
              {{ form.course_code.label() }}
            </div>
            <div class="form-floating mb-3">
              {{ form.course_title(class="form-control", placeholder="Course Title") }}
              {{ form.course_title.label() }}
            </div>
            <div class="form-floating mb-3">
              {{ form.level(class="form-control") }}
              {{ form.level.label() }}
            </div>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-lg btn-block btn-primary">
            Submit</button>
        </div>
      </div>
    </div>
  </div>
  
</body>
{% endblock %}

website/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
    integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <title>Home</title>
</head>
<body>
  <div class="container">
    <br>
    <a class="btn btn-primary btn-lg" href="/lecturer" role="button">I'm a Lecturer</a>
    <a class="btn btn-secondary btn-lg" href="/student-login" role="button">I'm a Student</a>
  </div>

  <script 
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" 
    crossorigin="anonymous"
  ></script>
</body>
</html>

website/templates/lecturer.html
{% extends "base.html" %}

{% block title %}
  Lecturers
{% endblock %}

{% block content %}
<body class="text-center">
<h2>A page to show login & signup for the lecturers <br>and some information about the usage of the system</h2>
</body>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}
    Sign Up
{% endblock %}

{% block content %}
<body class="text-center">
<h1>Login</h1>
<form method="POST" class="form-register">
  {{ form.hidden_tag() }}
  <div class="form-floating mb-3">
    {{ form.staff_no(class="form-control", placeholder="Staff Number") }}
    {{ form.staff_no.label() }}
  </div>
  <div class="form-floating mb-3">
    {{ form.password(class="form-control", placeholder="Password") }}
    {{ form.password.label() }}
  </div>
  <div class="checkbox mb-4">
    <h6>Do not have an account?</h6>
    <a class="btn btn-sm btn-secondary" href="{{ url_for('auth.sign_up') }}">Sign Up</a>
  </div>
  {{ form.submit(class="btn btn-lg btn-block btn-primary mb-3") }}

</form>
</body>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}
{% block title %}
    Sign Up
{% endblock %}

{% block content %}
<body class="text-center">
<h1>Register As a Lecturer</h1>

<form method="POST" class="form-register">
  {{ form.hidden_tag() }}
  <div class="form-floating mb-3">
    {{ form.staff_no(class="form-control", placeholder="Staff Number") }}
    {{ form.staff_no.label() }}
  </div>
  <div class="form-floating mb-3">
    {{ form.first_name(class="form-control", placeholder="First Name") }}
    {{ form.first_name.label() }}
  </div>
  <div class="form-floating mb-3">
    {{ form.last_name(class="form-control", placeholder="Last Name") }}
    {{ form.last_name.label() }}
  </div>
  <div class="form-floating mb-3">
    {{ form.email_address(class="form-control", placeholder="Email Address") }}
    {{ form.email_address.label() }}
  </div>
  <div class="form-floating mb-3">
    {{ form.password(class="form-control", placeholder="Password") }}
    {{ form.password.label() }}
  </div>
  <div class="form-floating mb-3">
    {{ form.confirm_password(class="form-control", placeholder="Password") }}
    {{ form.confirm_password.label() }}
  </div>
  <div class="form-floating mb-3">
    {{ form.faculty(class="form-control", onchange="updateDepts(this)") }}
    {{ form.faculty.label() }}
  </div>
  <div class="form-floating mb-3">
    {{ form.department(class="form-control") }}
    {{ form.department.label() }}
  </div>
  <br>
  <div class="checkbox mb-4">
    <h6>Already have an Account?</h6>
    <a class="btn btn-sm btn-secondary" href="{{ url_for('auth.login') }}">Log In</a>
  </div>
  {{ form.submit(class="btn btn-lg btn-block btn-primary mb-3") }}
</form>

</body>
{% endblock %}

website/templates/student_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
    integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <title>Dashboard</title>

  <script 
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" 
  crossorigin="anonymous"
  ></script>

  <script
  type="text/javascript"
  src="{{ url_for('static', filename='index.js') }}"
  ></script>

</head>

<body>
  <div class="container text-center">
    <h1 class="mb-2">Welcome {{ user.first_name }} {{ user.last_name }}</h1>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" 
    data-bs-target="#enrollModal">Enroll Fingerprint
  </button>
    <div class="text-start">

      <h4>Matric Number: {{ user.matric_no }} </h4><br>

      <h3>Courses Registerd:</h3>
      <ol>
      {% for enrolled_courses, courses in enrolled %}
      <li>{{ enrolled_courses.course_code}}: {{ courses.course_title }}</li>
      {% endfor %}
      </ol>

      {% if not disabled %}
      <h3>Add New Courses:</h3>
      <div class="content-section">
      <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.courses }}
        {{ form.submit(class="btn btn-block btn-primary mb-3", disabled=disabled) }}
      </form>
      </div>
      {% endif %}

    </div>
  </div>

  <!-- Add course Modal -->
  <div class="modal fade modal-lg" id="enrollModal" tabindex="-1" 
    aria-labelledby="addCourseModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="addCourseModalLabel">
            Enroll your Fingerprint</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" 
            aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <h4>Click the button below and place your finger on the sensor twice, \
            place your finger again when the light goes off..</h4>
          <button type="button" class="btn btn-primary btn-lg" id="enrollButton">
            Start Enrollment</button>
          <p id="enroll-message"></p>
        </div>

  <script 
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" 
  crossorigin="anonymous"
  ></script>
</body>
</html>

website/templates/student_enroll.html
{% extends "base.html" %}
{% block title %}
    Enroll
{% endblock %}

{% block content %}
<body class="text-center" onload="facultyList()">
<h1>Register As a Student</h1>

<form method="POST" class="form-register">
  {{ form.hidden_tag() }}
  <div class="form-floating mb-3">
    {{ form.matric_no(class="form-control", placeholder="Matric Number") }}
    {{ form.matric_no.label() }}
  </div>
  <div class="form-floating mb-3">
    {{ form.first_name(class="form-control", placeholder="First Name") }}
    {{ form.first_name.label() }}
  </div>
  <div class="form-floating mb-3">
    {{ form.last_name(class="form-control", placeholder="Last Name") }}
    {{ form.last_name.label() }}
  </div>
  <div class="form-floating mb-3">
    {{ form.level(class="form-control") }}
    {{ form.level.label() }}
  </div>
  <div class="form-floating mb-3">
    {{ form.faculty(class="form-control", onchange="updateDepts(this)") }}
    {{ form.faculty.label() }}
  </div>
  <div class="form-floating mb-3">
    {{ form.department(class="form-control") }}
    {{ form.department.label() }}
  </div>
  <br>
  <div class="checkbox mb-4">
    <h6>Already enrolled?</h6>
    <a class="btn btn-sm btn-secondary" href="{{ url_for('auth.student_login') }}">Log In</a>
  </div>
  {{ form.submit(class="btn btn-lg btn-block btn-primary mb-3") }}
</form>

</body>
{% endblock %}

website/templates/student_login.html
{% extends "base.html" %}
{% block title %}
    Sign Up
{% endblock %}

{% block content %}
<body class="text-center">
<h1>Login</h1>
<form method="POST" class="form-register">
  {{ form.hidden_tag() }}
  <div class="form-floating mb-3">
    {{ form.matric_no(class="form-control", placeholder="Matric Number") }}
    {{ form.matric_no.label() }}
  </div>
  <div class="form-floating mb-3">
    {{ form.first_name(class="form-control", placeholder="Password") }}
    {{ form.first_name.label() }}
  </div>
  <div class="checkbox mb-4">
    <h6>Not enrolled yet?</h6>
    <a class="btn btn-sm btn-secondary" href="{{ url_for('auth.enroll') }}">Enroll</a>
  </div>
  {{ form.submit(class="btn btn-lg btn-block btn-primary mb-3") }}

</form>
</body>
{% endblock %}